services:
  backend-manager:
    restart: always
    build:
      context: backend
      dockerfile: DockerfileManager
    volumes:
      - ".data:/.data"
      - ".env:/.env"

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerfileFrontend
      args:
        VITE_API_URL: /api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
